### PR TITLE
Fixed #776 and #777 (fixed translations)

### LINKED ISSUE #776: Blocks : the letter B must be uppercase
Blocks : the letter B must be uppercase
blocks

### PR DESCRIPTION
**Pull request by mickaelandrieu**
@ndufreche the BbCoreJs build sound broken on test poppin creation :/ not related to this pr.

```
PopInManager specs
   - Test creation of a pop-in...>> Error: require: 'null' is not an object (evaluating 'wrapper.appendChild') at
>> _SpecRunner.html:36 
>> .grunt/grunt-contrib-jasmine/require.js:12 v
>> .grunt/grunt-contrib-jasmine/require.js:19 
>> .grunt/grunt-contrib-jasmine/require.js:23 
>> .grunt/grunt-contrib-jasmine/require.js:17 
>> .grunt/grunt-contrib-jasmine/require.js:26 
```

### CODE REVIEW

**Comment by fkroockmann** [comment]
Can you add a real description for your commit plz ?

**Comment by fkroockmann** [comment]
:+1: , Thanks @mickaelandrieu

**Comment by ndufreche** [comment]
@mickaelandrieu Is not really broken because no test fail but yes there is an error.

**Comment by ndufreche** [comment]
:+1:

**Comment by mickaelandrieu** [comment]
I just have updated commit message, ok for your explanation @ndufreche.

Thanks for review.

**Comment by ndufreche** [comment]
@mickaelandrieu I will take time next week to resolve the error

**Pull request merged**
