### PR TITLE
Forcing get pagination response to be an array

### PR DESCRIPTION
**Pull request by ndufreche**
I create this PR, because currently I have a problem with the response type in getCollectionAction from the User Rest Controller. This evol permit to avoid bad typing response from the server and help the JS to continuing working correctly.

I add a new function into Utils class castAsArray to transform an object into an array.
And I use that function into group and user controller to avoid the badly response type from the BackBee REST server.

### CODE REVIEW

**Comment by fkroockmann** [comment]
You can't fix it on PHP?

**Comment by ndufreche** [comment]
Nop, I have try during 1 day.

**Comment by mickaelandrieu** [comment]
for now, I think we can "deal with it", and remove this patch when the PHP will become more "consistent": what do you think @fkroockmann  ?

**Comment by ndufreche** [comment]
I think, is not a bad practice to do this thing. That permit to avoid some errors and keep the JS execution safe.

**Comment by mickaelandrieu** [comment]
:+1:

**Pull request merged**
