### PR TITLE
#609 - Logout tests

### PR DESCRIPTION
**Pull request by flaviaF**

### CODE REVIEW

**Comment by fkroockmann** [comment]
Can you create that on a logout file ?

**Comment by cmarianhodis** [comment]
:+1:

**Comment by fkroockmann** [comment]
Ok maybe rename this file to authentication.js ?

**Comment by cmarianhodis** [comment]
:+1: for that idea

@flaviaF please rename the file

**Comment by cmarianhodis** [comment]
@flaviaF please squash your commits

**Pull request merged**
