### PR TITLE
[RFR] Added translations for bundle apps

### PR DESCRIPTION
**Pull request by mickaelandrieu**
See #266 -> apps -> bundle

### CODE REVIEW

**Comment by fkroockmann** [comment]
:+1:

**Comment by ndufreche** [comment]
No fr translation ?

**Comment by mickaelandrieu** [comment]
Nice catch @ndufreche .

French translations added and pull request rebased.

Ready to merge ? :)

**Comment by ndufreche** [comment]
thanks @mickaelandrieu :+1:

**Pull request merged**
