### PR TITLE
[proposal] update link selector

### PR DESCRIPTION
**Pull request by ndufreche**
The actual system can suggest that the link selector is not working => #397 

On this proposal i request all the page and set has disable the pages how are not online to ease the visualization.

### CODE REVIEW

**Comment by fkroockmann** [comment]
Deleted page must be not shown.

**Comment by ndufreche** [comment]
update:

```js
'state': [1, 3],
```

**Comment by mickaelandrieu** [comment]
is it ready for merge ?

**Comment by ndufreche** [comment]
Yes @fkroockmann is ok.

**Comment by mickaelandrieu** [comment]
thank you @ndufreche

**Pull request merged**
