### PR TITLE
[rest] the rest client have to specified the accept parameter. #273

### PR DESCRIPTION
**Pull request by ndufreche**
Little update on REST driver to add the accept parameter in HTTP header.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
:+1:

**Comment by ndufreche** [comment]
Before tests, the accept parameter still overwritable.

**Comment by mickaelandrieu** [comment]
Thanks, I will provide an json error response so :)

**Comment by ndufreche** [comment]
Pretty cool :+1:

**Pull request merged**
