### PR TITLE
[RFR] Added translations for Page application

### PR DESCRIPTION
**Pull request by mickaelandrieu**
- [x] translations en_US for contribution/manage pages
- [x] translations fr_FR for contribution/manage pages

See #266 -> apps -> page

### CODE REVIEW

**Comment by fkroockmann** [comment]
:+1:

**Comment by ndufreche** [comment]
:+1:  good job.
@mickaelandrieu  Squash your commit and i will merge it soon

**Comment by mickaelandrieu** [comment]
done ;)

**Comment by ndufreche** [comment]
You can update the translate issue #266

**Pull request merged**
