### PR TITLE
[RFR] Added translations for Contribution application

### PR DESCRIPTION
**Pull request by mickaelandrieu**
See #266 -> app -> contribution

- [x] en_US translations (templates)
- [x] fr_FR translations (templates)

### CODE REVIEW

**Comment by fkroockmann** [comment]
:+1:

**Comment by ndufreche** [comment]
:+1: good job.
@mickaelandrieu Squash your commit and i will merge it soon

**Comment by mickaelandrieu** [comment]
Done ;)

**Comment by ndufreche** [comment]
Thanks @mickaelandrieu

**Pull request merged**
