### PR TITLE
Fixed #543 - change titles of sections

### LINKED ISSUE #543: title of sections
for user management write Users management
for contribution write Contribution
for Extensions write Extensions

### PR DESCRIPTION
**Pull request by mickaelandrieu**
See #543 only change the translation keys.

### CODE REVIEW

**Comment by fkroockmann** [comment]
Maybe, yesterday my PR was merged before travis work. Can you add 'return file' at the end of event "sending" ?

Sorry dude.

**Comment by fkroockmann** [comment]
:+1:

**Comment by hbaptiste** [comment]
@fkroockmann I added /*jslint unparam: true*/ on the top of the file. The "file" param is not used.
But, as xhr is the second parameter, you have to leave it (the file param).

**Comment by mickaelandrieu** [comment]
@ndufreche what do you have to do finaly ? 
I disagree to add some specific lint configuration into my file, can you make a quick patch on master branch to fix the build ? Then I rebase and the world will become a better place :p

**Comment by ndufreche** [comment]
@mickaelandrieu this rule it's get some return on unused variable to try keeping the code clean. But sometimes, some API are not clearly corresponding to our's criteria and we have to do some creepy thinks. In this case we have 3 solutions :
- specific jslint configuration into the file
- return unused param or delete it
- use Arguments to get only the second parameter

You can choose your preferred method, I will fix the file with this method.

**Comment by mickaelandrieu** [comment]
@ndufreche I prefer the second you may return a boolean ? thank you :)

**Comment by fkroockmann** [comment]
Yes, use "return file;" at the end :)

**Comment by mickaelandrieu** [comment]
@ndufreche tell me when I need to rebase.

**Comment by ndufreche** [comment]
@mickaelandrieu you can rebase

**Comment by mickaelandrieu** [comment]
=============================== Coverage summary ===============================
Statements   : 21.9% ( 749/3420 )
Branches     : 16.4% ( 193/1177 )
Functions    : 23.31% ( 228/978 )
Lines        : 21.91% ( 749/3418 )
================================================================================

76 specs in 2.697s.
>> 0 failures


=> Nice fix @ndufreche

**Comment by ndufreche** [comment]
cool :+1:

**Pull request merged**
