### PR TITLE
Creating a method to set the title pane

### PR DESCRIPTION
**Pull request by ndufreche**
- [x] Creating a method to set the title pane
- [x] use this method to update the title pane
 - [x] content application
 - [x] bundle application
 - [x] user application

### CODE REVIEW

**Comment by fkroockmann** [comment]
Can you use a real translation ?

**Comment by ndufreche** [comment]
Core.get('trans') is the real translation.
this function "function (value) {return value; };" is just in case of the translator is not available

**Comment by fkroockmann** [comment]
I mean with : trans('Bundle administration')

**Comment by ndufreche** [comment]
O.o ok :smile:

**Comment by fkroockmann** [comment]
:+1:

**Pull request merged**
