### PR TITLE
REFS #463 - login form display and behavior

### PR DESCRIPTION
**Pull request by mickaelandrieu**
* Added Log in title for the popin
* Added windows reloading to be able to call again the login form after closed it
* Add ``@todo`` for the form translation (out of scope)

### CODE REVIEW

**Comment by ndufreche** [comment]
Radical blaze but ok :+1:

**Comment by mickaelandrieu** [comment]
:cat2:

**Comment by ndufreche** [comment]
:hankey:

**Comment by mickaelandrieu** [comment]
thanks for review @ndufreche

**Pull request merged**
