### PR TITLE
Improve displaying of page statuses

### PR DESCRIPTION
**Pull request by mickaelandrieu**
REFS #590 

Also, notice we need to merge https://github.com/backbee/BackBee/pull/418 in same time.

### CODE REVIEW

**Comment by ndufreche** [comment]
Strange think to add English translation into French catalog but :+1:

**Comment by mickaelandrieu** [comment]
@ndufreche nice catch, I forgot these ones :)

**Comment by fkroockmann** [comment]
:+1:

**Comment by mickaelandrieu** [comment]
@ndufreche you can merge :)

**Pull request merged**
