### PR TITLE
#76 new plugin Manager for content

### PR DESCRIPTION
**Pull request by hbaptiste**
PluginManager allows us to create plugins for contents.
Plugins can expose actions that will be shown above the selected content.
Plugins can also act in a more discrete way.

### CODE REVIEW

**Comment by ndufreche** [comment]
I see no commit to correct the issue #76, just merge history.

**Comment by ndufreche** [comment]
@hbaptiste can I close this PR, it seems be a fail PR ?

**Comment by mickaelandrieu** [comment]
@ndufreche we need this in BbCoreJs.
@hbaptiste please take time to correctly rebase this one ;)

**Comment by ndufreche** [comment]
I think, this PR is totally useless, there is no commit to correct the issue 73 and all commit are already merged in core js.
I close this PR

**Comment by mickaelandrieu** [comment]
@ndufreche is the plugin Manager part of CoreJs ?
@hbaptiste can you add docs ? I'm interested to do my own plugin now.

**Pull request closed without merging**
