### PR TITLE
Fixed #556 - Change bad credentials label

### LINKED ISSUE #556: error message when logged in
I tried to logg in with a fake login and password, and the message which appears is "Bad credentials"

Should we replace this message by something like : login or password incorrect. Please, try again. @clementbonfils

### PR DESCRIPTION
**Pull request by mickaelandrieu**
See #556 , changed "Bad credentials" to "login or password incorrect".

Notice: we don't have any access to the translator component atm.

### CODE REVIEW

**Comment by fkroockmann** [comment]
You have access to translator, you need to require : "require('tb.component/translator/main"

**Comment by fkroockmann** [comment]
:+1:

**Comment by fkroockmann** [comment]
Why you don't have access ?

**Comment by mickaelandrieu** [comment]
I don't know exactly, I've already have tested when I wanted to translate the authentication form, and the translator component didn't have access to the ToolBarBundle atm. If you have a tip, I will update my commit :)

**Comment by ndufreche** [comment]
because the session and the authentication are called before the translator

**Pull request merged**
