### PR TITLE
[RFR] Added translations for toolbar (main) app

### PR DESCRIPTION
**Pull request by mickaelandrieu**
- [x] en_US translations
- [x] fr_FR translations

### CODE REVIEW

**Comment by ndufreche** [comment]
:+1:

**Comment by mickaelandrieu** [comment]
@ndufreche would you mind to merge this one ? I update the related issue (https://github.com/backbee/BbCoreJs/issues/266)

**Comment by ndufreche** [comment]
Yep just manipulation fail.

**Comment by ndufreche** [comment]
@mickaelandrieu you can update #266 issue

**Pull request merged**
