### PR TITLE
[Component] [FormBuilder] + add media element

### PR DESCRIPTION
**Pull request by fkroockmann**
mediaSelector is a new element of formbuilder, he can add one or several medias.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
oups, you need a little rebase @fkroockmann :)

**Comment by fkroockmann** [comment]
wrong remote ^^

**Comment by ndufreche** [comment]
:+1:

**Comment by fkroockmann** [comment]
You can merge :)

**Comment by mickaelandrieu** [comment]
thanks !

**Pull request merged**
