### PR TITLE
[user] Add close function with popin destruction

### PR DESCRIPTION
**Pull request by ndufreche**
This little tricks permit to remove some bugs in the user application identified by @clementbonfils in issue #303

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
ping @fkroockmann I don't see any weird thing, but I don't know well this part of core.
Please review

**Comment by fkroockmann** [comment]
It's not a part of core but its ok for me. :+1:

**Comment by fkroockmann** [comment]
Can you prefix your PR and commit by [User] ?

**Comment by ndufreche** [comment]
rebased and renamed

**Comment by mickaelandrieu** [comment]
you can merge ;) thank you @ndufreche

**Pull request merged**
