### PR TITLE
Update toolbar skin

### PR DESCRIPTION
**Pull request by fkroockmann**
toolbar

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@fkroockmann can you put a screenshot please ? :)

**Comment by fkroockmann** [comment]
On description @mickaelandrieu

**Comment by mickaelandrieu** [comment]
thank you, it's nice :+1:

**Comment by clementbonfils** [comment]
- [ ] Display block icones smaller in the "edit" form
- [ ] Render mode of elements are a bit hidden in mediatheque and content selector
- [ ] scroll bar in mediatheque and content selector goes above the number of element's selector
- [ ] State of page are badly displayed in the link selector
- [ ] Delete render mode of item in link selector
- [ ] Change date picker plug in for scheduling
- [ ] Reduce a few pixels the hight of the toolbar at the bottom
- [ ] Open all the pop in a bit higher in the page, at the toolbar lower limit
- [ ] No selected state on level 1 when connecting
- [ ] Previous section selected remains orange even when not selected anymore
- [ ] Bundle icones are too big 
- [ ] Disable "see my extensions" button when an extension is already opened 
- [ ] Delete arrows at the right side of the bundle description 
- [ ] List mode in content selector is KO
- [ ] Center the elements in content selector
- [ ] website selector in content selector is not skinned
- [ ] Hide date picker when re cliking on the calendar
- [ ] Change media selector icone and get it centered in the button
- [ ] Generalize a one and only type of confirmation pop in

**Pull request merged**
